#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "moves.hpp"
#include "pokemon.hpp"
#include "../rules/rules.hpp"

static Move defs[] = {
    {MT_UNDEFINE, "Undefined", T_NOT_SET, 0, 0, C_STATUS, 0},
    {MT_POUND, "Pound", T_NORMAL, 35, 40, C_PHYSICAL, 100},
    {MT_KARATE_CHOP, "Karate mChop", T_NORMAL, 25, 50, C_PHYSICAL, 100},
    {MT_DOUBLE_SLAP, "Double Slap", T_NORMAL, 10, 15, C_PHYSICAL, 85},
    {MT_COMET_PUNCH, "Comet Punch", T_NORMAL, 15, 18, C_PHYSICAL, 85},
    {MT_MEGA_PUNCH, "Mega Punch", T_NORMAL, 20, 80, C_PHYSICAL, 85},
    {MT_PAY_DAY, "Pay Day", T_NORMAL, 20, 40, C_PHYSICAL, 100},
    {MT_FIRE_PUNCH, "Fire Punch", T_FIRE, 15, 75, C_PHYSICAL, 100},
    {MT_ICE_PUNCH, "Ice Punch", T_ICE, 15, 75, C_PHYSICAL, 100},
    {MT_THUNDER_PUNCH, "Thunder Punch", T_ELECTRIC, 15, 75, C_PHYSICAL, 100},
    {MT_SCRATCH, "Scratch", T_NORMAL, 35, 40, C_PHYSICAL, 100},
    {MT_VISE_GRIP, "Vise Grip", T_NORMAL, 30, 55, C_PHYSICAL, 100},
    {MT_GUILLOTINE, "Guillotine", T_NORMAL, 5, 0, C_PHYSICAL, 30},
    {MT_RAZOR_WIND, "Razor Wind", T_NORMAL, 10, 80, C_SPECIAL, 75},
    {MT_SWORDS_DANCE, "Swords Dance", T_NORMAL, 30, 0, C_STATUS, 0},
    {MT_CUT, "Cut", T_NORMAL, 30, 50, C_PHYSICAL, 95},
    {MT_GUST, "Gust", T_NORMAL, 35, 40, C_SPECIAL, 100},
    {MT_WING_ATTACK, "Wing Attack", T_FLYING, 35, 35, C_PHYSICAL, 100},
    {MT_WHIRLWIND, "Whirlwind", T_NORMAL, 20, 0, C_STATUS, 85},
    {MT_FLY, "Fly", T_FLYING, 15, 70, C_PHYSICAL, 95},
    {MT_BIND, "Bind", T_NORMAL, 20, 15, C_PHYSICAL, 75},
    {MT_SLAM, "Slam", T_NORMAL, 20, 80, C_PHYSICAL, 75},
    {MT_VINE_WHIP, "Vine ,Whip", T_GRASS, 10, 35, C_PHYSICAL, 100},
    {MT_STOMP, "Stomp", T_NORMAL, 20, 65, C_PHYSICAL, 100},
    {MT_DOUBLE_KICK, "Double Kick", T_FIGHTING, 30, 30, C_PHYSICAL, 100},
    {MT_MEGA_KICK, "Mega Kick", T_NORMAL, 5, 120, C_PHYSICAL, 75},
    {MT_JUMP_KICK, "Jump Kick", T_FIGHTING, 25, 70, C_PHYSICAL, 95},
    {MT_ROLLING_KICK, "Rolling mKick", T_FIGHTING, 15, 60, C_PHYSICAL, 85},
    {MT_SAND_ATTACK, "Sand Attack", T_NORMAL, 15, 0, C_STATUS, 100},
    {MT_HEADBUTT, "Headbutt", T_NORMAL, 15, 70, C_PHYSICAL, 100},
    {MT_HORN_ATTACK, "Horn Attack", T_NORMAL, 25, 65, C_PHYSICAL, 100},
    {MT_FURY_ATTACK, "Fury Attack", T_NORMAL, 20, 15, C_PHYSICAL, 85},
    {MT_HORN_DRILL, "Horn Drill", T_NORMAL, 5, 0, C_PHYSICAL, 30},
    {MT_TACKLE, "Tackle", T_NORMAL, 35, 35, C_PHYSICAL, 95},
    {MT_BODY_SLAM, "Body Slam", T_NORMAL, 15, 85, C_PHYSICAL, 100},
    {MT_WRAP, "Wrap", T_NORMAL, 20, 15, C_PHYSICAL, 85},
    {MT_TAKE_DOWN, "Take ,Down", T_NORMAL, 20, 90, C_PHYSICAL, 85},
    {MT_THRASH, "Thrash", T_NORMAL, 20, 90, C_PHYSICAL, 100},
    {MT_DOUBLE_EDGE, "Double-Edge", T_NORMAL, 15, 100, C_PHYSICAL, 100},
    {MT_TAIL_WHIP, "Tail Whip", T_NORMAL, 30, 0, C_STATUS, 100},
    {MT_POISON_STING, "Poison_Sting", T_POISON, 35, 15, C_PHYSICAL, 100},
    {MT_TWINEEDLE, "Twineedle", T_BUG, 20, 25, C_PHYSICAL, 100},
    {MT_PIN_MISSILE, "Pin_Missile", T_BUG, 20, 14, C_PHYSICAL, 85},
    {MT_LEER, "Leer", T_NORMAL, 30, 0, C_STATUS, 100},
    {MT_BITE, "Bite", T_NORMAL, 25, 60, C_PHYSICAL, 100},
    {MT_GROWL, "Growl", T_NORMAL, 40, 0, C_STATUS, 100},
    {MT_ROAR, "Roar", T_NORMAL, 20, 0, C_STATUS, 100},
    {MT_SING, "Sing", T_NORMAL, 15, 0, C_STATUS, 55},
    {MT_SUPERSONIC, "Supersonic", T_NORMAL, 20, 20, C_STATUS, 55},
    {MT_SONIC_BOOM, "Sonic Boom", T_NORMAL, 20, 0, C_SPECIAL, 90},
    {MT_DISABLE, "Disable", T_NORMAL, 20, 0, C_STATUS, 55},
    {MT_ACID, "Acid", T_POISON, 30, 40, C_SPECIAL, 100},
    {MT_EMBER, "Ember", T_FIRE, 25, 40, C_SPECIAL, 100},
    {MT_FLAMETHROWER, "Flamethrower", T_FIRE, 15, 95, C_SPECIAL, 100},
    {MT_MIST, "Mist", T_ICE, 30, 0, C_STATUS, 0},
    {MT_WATER_GUN, "Water Gun", T_WATER, 25, 40, C_SPECIAL, 100},
    {MT_HYDRO_PUMP, "Hydro Pump", T_WATER, 5, 120, C_SPECIAL, 80},
    {MT_SURF, "Surf", T_WATER, 15, 95, C_SPECIAL, 100},
    {MT_ICE_BEAM, "Ice Beam", T_ICE, 10, 95, C_SPECIAL, 100},
    {MT_BLIZZARD, "Blizzard", T_ICE, 5, 120, C_SPECIAL, 90},
    {MT_PSYBEAM, "Psybeam", T_PSYCHIC, 20, 65, C_SPECIAL, 100},
    {MT_BUBBLE_BEAM, "Bubble Beam", T_WATER, 20, 65, C_SPECIAL, 100},
    {MT_AURORA_BEAM, "Aurora Beam", T_ICE, 20, 65, C_SPECIAL, 100},
    {MT_HYPER_BEAM, "Hyper Beam", T_NORMAL, 5, 150, C_SPECIAL, 90},
    {MT_PECK, "Peck", T_FLYING, 35, 35, C_PHYSICAL, 100},
    {MT_DRILL_PECK, "Drill Peck", T_FLYING, 20, 80, C_PHYSICAL, 100},
    {MT_SUBMISSION, "Submission", T_FIGHTING, 25, 80, C_PHYSICAL, 80},
    {MT_LOW_KICK, "Low Kick", T_FIGHTING, 20, 50, C_PHYSICAL, 90},
    {MT_COUNTER, "Counter", T_FIGHTING, 20, 0, C_PHYSICAL, 100},
    {MT_SEISMIC_TOSS, "Seismic Toss", T_FIGHTING, 20, 0, C_PHYSICAL, 100},
    {MT_STRENGTH, "Strength", T_NORMAL, 15, 80, C_PHYSICAL, 100},
    {MT_ABSORB, "Absorb", T_GRASS, 20, 20, C_SPECIAL, 100},
    {MT_MEGA_DRAIN, "Mega Drain", T_GRASS, 10, 40, C_SPECIAL, 100},
    {MT_LEECH_SEED, "Leech Seed", T_GRASS, 10, 0, C_STATUS, 90},
    {MT_GROWTH, "Growth", T_NORMAL, 40, 0, C_STATUS, 0},
    {MT_RAZOR_LEAF, "Razor Leaf", T_GRASS, 25, 55, C_PHYSICAL, 95},
    {MT_SOLAR_BEAM, "Solar Beam", T_GRASS, 10, 120, C_SPECIAL, 100},
    {MT_POISON_POWDER, "Poison Powder", T_POISON, 35, 0, C_STATUS, 75},
    {MT_STUN_SPORE, "Stun Spore", T_GRASS, 30, 0, C_STATUS, 75},
    {MT_SLEEP_POWDER, "Sleep Powder", T_GRASS, 15, 0, C_STATUS, 75},
    {MT_PETAL_DANCE, "Petal Dance", T_GRASS, 10, 70, C_SPECIAL, 100},
    {MT_STRING_SHOT, "String Shot", T_BUG, 40, 0, C_STATUS, 95},
    {MT_DRAGON_RAGE, "Dragon Rage", T_DRAGON, 10, 40, C_SPECIAL, 100},
    {MT_FIRE_SPIN, "Fire Spin", T_FIRE, 15, 15, C_SPECIAL, 70},
    {MT_THUNDER_SHOCK, "Thunder Shock", T_ELECTRIC, 30, 40, C_SPECIAL, 100},
    {MT_THUNDERBOLT, "Thunderbolt", T_ELECTRIC, 15, 95, C_SPECIAL, 100},
    {MT_THUNDER_WAVE, "Thunder_Wave", T_ELECTRIC, 20, 0, C_STATUS, 100},
    {MT_THUNDER, "Thunder", T_ELECTRIC, 10, 120, C_SPECIAL, 70},
    {MT_ROCK_THROW, "Rock_Throw", T_ROCK, 15, 50, C_PHYSICAL, 65},
    {MT_EARTHQUAKE, "Earthquake", T_GROUND, 10, 100, C_PHYSICAL, 100},
    {MT_FISSURE, "Fissure", T_GROUND, 5, 0, C_PHYSICAL, 30},
    {MT_DIG, "Dig", T_GROUND, 10, 100, C_PHYSICAL, 100},
    {MT_TOXIC, "Toxic", T_POISON, 10, 0, C_STATUS, 85},
    {MT_CONFUSION, "Confusion", T_PSYCHIC, 25, 50, C_SPECIAL, 100},
    {MT_PSYCHIC, "Psychic", T_PSYCHIC, 10, 90, C_SPECIAL, 100},
    {MT_HYPNOSIS, "Hypnosis", T_PSYCHIC, 20, 0, C_STATUS, 70},
    {MT_MEDITATE, "Meditate", T_PSYCHIC, 40, 0, C_STATUS, 0},
    {MT_AGILITY, "Agility", T_PSYCHIC, 30, 0, C_STATUS, 0},
    {MT_QUICK_ATTACK, "Quick Attack", T_NORMAL, 30, 40, C_PHYSICAL, 100},
    {MT_RAGE, "Rage", T_NORMAL, 20, 20, C_PHYSICAL, 100},
    {MT_TELEPORT, "Teleport", T_PSYCHIC, 20, 0, C_STATUS, 0},
    {MT_NIGHT_SHADE, "Night_Shade", T_GHOST, 15, 0, C_SPECIAL, 100},
    {MT_MIMIC, "Mimic", T_NORMAL, 10, 0, C_STATUS, 100},
    {MT_SCREECH, "Screech", T_NORMAL, 40, 0, C_STATUS, 85},
    {MT_DOUBLE_TEAM, "Double_Team", T_NORMAL, 15, 0, C_STATUS, 0},
    {MT_RECOVER, "Recover", T_NORMAL, 20, 0, C_STATUS, 0},
    {MT_HARDEN, "Harden", T_NORMAL, 30, 0, C_STATUS, 0},
    {MT_MINIMIZE, "Minimize", T_NORMAL, 20, 0, C_STATUS, 0},
    {MT_SMOKESCREEN, "Smokescreen", T_NORMAL, 20, 0, C_STATUS, 100},
    {MT_CONFUSE_RAY, "Confuse Ray", T_GHOST, 10, 0, C_STATUS, 100},
    {MT_WITHDRAW, "Withdraw", T_WATER, 40, 0, C_STATUS, 0},
    {MT_DEFENSE_CURL, "Defense_Curl", T_NORMAL, 40, 0, C_STATUS, 0},
    {MT_BARRIER, "Barrier", T_PSYCHIC, 30, 0, C_STATUS, 0},
    {MT_LIGHT_SCREEN, "Light Screen", T_PSYCHIC, 30, 0, C_STATUS, 0},
    {MT_HAZE, "Haze", T_ICE, 30, 0, C_STATUS, 0},
    {MT_REFLECT, "Reflect", T_PSYCHIC, 20, 0, C_STATUS, 0},
    {MT_FOCUS_ENERGY, "Focus Energy", T_NORMAL, 30, 0, C_STATUS, 0},
    {MT_BIDE, "Bide", T_NORMAL, 10, 0, C_PHYSICAL, 100},
    {MT_METRONOME, "Metronome", T_NORMAL, 10, 0, C_STATUS, 0},
    {MT_MIRROR_MOVE, "Mirror Move", T_FLYING, 20, 0, C_STATUS, 0},
    {MT_SELF_DESTRUCT, "Self-Destruct", T_NORMAL, 5, 130, C_PHYSICAL, 100},
    {MT_EGG_BOMB, "Egg Bomb", T_NORMAL, 10, 100, C_PHYSICAL, 75},
    {MT_LICK, "Lick", T_GHOST, 30, 20, C_PHYSICAL, 100},
    {MT_SMOG, "Smog", T_POISON, 20, 20, C_SPECIAL, 70},
    {MT_SLUDGE, "Sludge", T_POISON, 20, 65, C_SPECIAL, 100},
    {MT_BONE_CLUB, "Bone Club", T_GROUND, 20, 65, C_PHYSICAL, 85},
    {MT_FIRE_BLAST, "Fire_Blast", T_FIRE, 5, 120, C_SPECIAL, 85},
    {MT_WATERFALL, "Waterfall", T_WATER, 15, 80, C_PHYSICAL, 100},
    {MT_CLAMP, "Clamp", T_WATER, 10, 35, C_PHYSICAL, 75},
    {MT_SWIFT, "Swift", T_NORMAL, 20, 60, C_SPECIAL, 0},
    {MT_SKULL_BASH, "Skull Bash", T_NORMAL, 15, 100, C_PHYSICAL, 100},
    {MT_SPIKE_CANNON, "Spike Cannon", T_NORMAL, 15, 20, C_PHYSICAL, 100},
    {MT_CONSTRICT, "Constrict", T_NORMAL, 35, 10, C_PHYSICAL, 100},
    {MT_AMNESIA, "Amnesia", T_PSYCHIC, 20, 0, C_STATUS, 0},
    {MT_KINESIS, "Kinesis", T_PSYCHIC, 15, 0, C_STATUS, 80},
    {MT_SOFT_BOILED, "Soft-Boiled", T_NORMAL, 10, 0, C_STATUS, 0},
    {MT_HIGH_JUMP_KICK, "High Jump Kick", T_FIGHTING, 20, 85, C_PHYSICAL, 90},
    {MT_GLARE, "Glare", T_NORMAL, 30, 0, C_STATUS, 75},
    {MT_DREAM_EATER, "Dream Eater", T_PSYCHIC, 15, 100, C_SPECIAL, 100},
    {MT_POISON_GAS, "Poison Gas", T_POISON, 40, 0, C_STATUS, 55},
    {MT_BARRAGE, "Barrage", T_NORMAL, 20, 15, C_PHYSICAL, 85},
    {MT_LEECH_LIFE, "Leech Life", T_BUG, 15, 20, C_PHYSICAL, 100},
    {MT_LOVELY_KISS, "Lovely Kiss", T_NORMAL, 10, 0, C_STATUS, 75},
    {MT_SKY_ATTACK, "Sky Attack", T_FLYING, 5, 140, C_PHYSICAL, 90},
    {MT_TRANSFORM, "Transform", T_NORMAL, 10, 0, C_STATUS, 0},
    {MT_BUBBLE, "Bubble", T_WATER, 30, 20, C_SPECIAL, 100},
    {MT_DIZZY_PUNCH, "Dizzy Punch", T_NORMAL, 10, 70, C_PHYSICAL, 100},
    {MT_SPORE, "Spore", T_GRASS, 15, 0, C_STATUS, 100},
    {MT_FLASH, "Flash", T_NORMAL, 20, 0, C_STATUS, 70},
    {MT_PSYWAVE, "Psywave", T_PSYCHIC, 15, 0, C_SPECIAL, 80},
    {MT_SPLASH, "Splash", T_NORMAL, 40, 0, C_STATUS, 0},
    {MT_ACID_ARMOR, "Acid Armor", T_POISON, 40, 0, C_STATUS, 0},
    {MT_CRABHAMMER, "Crabhammer", T_WATER, 10, 90, C_PHYSICAL, 85},
    {MT_EXPLOSION, "Explosion", T_NORMAL, 5, 170, C_PHYSICAL, 100},
    {MT_FURY_SWIPES, "Fury Swipes", T_NORMAL, 15, 18, C_PHYSICAL, 80},
    {MT_BONEMERANG, "Bonemerang", T_GROUND, 10, 50, C_PHYSICAL, 90},
    {MT_REST, "Rest", T_PSYCHIC, 10, 0, C_STATUS, 0},
    {MT_ROCK_SLIDE, "Rock  Slide", T_ROCK, 10, 75, C_PHYSICAL, 90},
    {MT_HYPER_FANG, "Hyper Fang", T_NORMAL, 15, 80, C_PHYSICAL, 90},
    {MT_SHARPEN, "Sharpen", T_NORMAL, 30, 0, C_STATUS, 0},
    {MT_CONVERSION, "Conversion", T_NORMAL, 30, 0, C_STATUS, 0},
    {MT_TRI_ATTACK, "Tri Attack", T_NORMAL, 10, 80, C_SPECIAL, 100},
    {MT_SUPER_FANG, "Super Fang", T_NORMAL, 10, 0, C_PHYSICAL, 90},
    {MT_SLASH, "Slash", T_NORMAL, 20, 70, C_PHYSICAL, 100},
    {MT_SUBSTITUTE, "Substitute", T_NORMAL, 10, 0, C_STATUS, 0},
    {MT_STRUGGLE, "Struggle", T_NORMAL, 10, 50, C_PHYSICAL, 100},
};

Move *getMoves(int *count)
{
    *count = sizeof(defs) / sizeof(defs[0]);
    return defs;
}
Move *getMoveById(MoveId id)
{
    assert(id >= 0 && id < (sizeof(defs) / sizeof(defs[0])));
    return &defs[id];
}

